### ISSUE TITLE
404 using github.io domain

### ISSUE THREAD

**Issue by laurenball** [brooksbecton/7-wonders-calc#13]
![4oh4](https://user-images.githubusercontent.com/16344962/119748707-7fcb4600-be63-11eb-906c-50fe1a6892f7.png)

using https://brooksbecton.github.io/7-wonders-calc/
browser: firefox, chrome, brave
OS: windows 10

no issues when loading from https://harveythegoodboy.xyz/

**Comment by brooksbecton** [comment]
No long supporting github urls. 

New URL: https://www.7wonderscalculator.com/
